"""initial_schema

Revision ID: 4e26cf760917
Revises: 
Create Date: 2026-05-14 10:19:43.146676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e26cf760917'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('subject', sa.String(length=254), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event'), 'audit_logs', ['event'], unique=False)
    op.create_index(op.f('ix_audit_logs_ts'), 'audit_logs', ['ts'], unique=False)
    op.create_table('instruments',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('security_type', sa.String(length=8), nullable=False),
    sa.Column('currency', sa.String(length=4), nullable=False),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('min_trade_vol', sa.Integer(), nullable=False),
    sa.Column('maturity_date', sa.String(length=10), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('put_or_call', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('security_id')
    )
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_table('market_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('best_bid', sa.Float(), nullable=True),
    sa.Column('best_ask', sa.Float(), nullable=True),
    sa.Column('bid_qty', sa.BigInteger(), nullable=True),
    sa.Column('ask_qty', sa.BigInteger(), nullable=True),
    sa.Column('last_trade_price', sa.Float(), nullable=True),
    sa.Column('last_trade_qty', sa.BigInteger(), nullable=True),
    sa.Column('vwap', sa.Float(), nullable=True),
    sa.Column('total_traded_qty', sa.BigInteger(), nullable=True),
    sa.Column('total_traded_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_security_id'), 'market_snapshots', ['security_id'], unique=False)
    op.create_index(op.f('ix_market_snapshots_ts'), 'market_snapshots', ['ts'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=12), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.BigInteger(), nullable=False),
    sa.Column('aggressor_side', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_security_id'), 'trades', ['security_id'], unique=False)
    op.create_index(op.f('ix_trades_ts'), 'trades', ['ts'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_trades_ts'), table_name='trades')
    op.drop_index(op.f('ix_trades_security_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_market_snapshots_ts'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_security_id'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_audit_logs_ts'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
